### ISSUE TITLE
Jasonette-Web app deployment

### ISSUE THREAD

**Issue by tomcam** [Jasonette/Jasonette-Web#5]
So how exactly would one deploy a Jasonette-Web app? Is it a single HTML file that calls the local webview somehow?

**Comment by gliechtenstein** [comment]
Just to be clarify, Jasonette-iOS and Jasonette-Android are native app development frameworks that use JSON markup.

Jasonette-Web is NOT for building mobile apps. It's for replicating the same rendered results on a regular web browser setting. So it's not meant for building an HTML5 phonegap type app. It's for actually building a replica web version of the mobile apps, which can be rendered on a browser or can be embedded in a website or anywhere JavaScript can be rendered.

**Comment by gliechtenstein** [comment]
As for how to use Jasonette-Web in a web setting, you can refer to https://github.com/Jasonette/Jasonette-Web#installation

**Comment by tomcam** [comment]
Thanks for the answer. That makes a ton of sense to me now.
